# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee0192bb8726c0d8922d37e0566ee4cc5b2b116076d16fcf62fbe20e3e50120d5fe11f28b9830908c06c6f13d930db24be34ff1ee0c108558a3855fac3b36c7

test:
  secret_key_base: 1824a9a143b484955644bc9b2f18d333991055002c955fb1e846842c8617b9407c6b223defec58c5603057a2ae50e979c69a384b52fca494e66176225bdee829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
